# Generated by Django 5.2 on 2025-04-13 15:14

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Назва категорії')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис категорії')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='category_icons/', verbose_name='Іконка категорії')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
            ],
            options={
                'verbose_name': 'Категорія',
                'verbose_name_plural': 'Категорії',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Назва товару')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)], verbose_name='Ціна')),
                ('stock_quantity', models.PositiveIntegerField(default=0, verbose_name='Кількість на складі')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Рекомендований товар')),
                ('discount_percentage', models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)], verbose_name='Відсоток знижки')),
                ('status', models.CharField(choices=[('available', 'В наявності'), ('out_of_stock', 'Немає в наявності'), ('coming_soon', 'Скоро у продажу'), ('discontinued', 'Знято з виробництва')], default='available', max_length=20, verbose_name='Статус')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Опис товару')),
                ('specifications', models.JSONField(blank=True, null=True, verbose_name='Характеристики')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product_images/', verbose_name='Зображення товару')),
                ('size', models.CharField(blank=True, choices=[('S', 'Маленький'), ('M', 'Середній'), ('L', 'Великий'), ('XL', 'Дуже великий')], max_length=2, null=True, verbose_name='Розмір')),
                ('weight', models.FloatField(blank=True, help_text='Вага товару в кілограмах', null=True, verbose_name='Вага')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата створення')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата оновлення')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main_app.category', verbose_name='Категорія')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товари',
                'ordering': ['-created_at'],
            },
        ),
    ]
